environment:
  matrix:
    - nodejs_version: 14
    - nodejs_version: 16

platform:
  - x86
  - x64

install:
  # https://www.appveyor.com/docs/lang/nodejs-iojs/#installing-any-version-of-nodejs-or-iojs
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm run wintest
